# Site setting 
title: "Comprehensive Workstation Configuration Guide"
subtitle: "Step-by-Step Instructions for Pre-Domain Setup, Domain Joining, and Post-Configuration"
description: "This document is a detailed guide for IT professionals tasked with setting up and configuring workstations. This work was the resulte of collaboration (Mohammed Mamdouh), (Hamzah Alanazi),and Thanks to (Rayed Ammorah)." 
author: "Khalid Alkhaldi"
theme: minima
copyright: "© 2024 AJF FEs"

collaborators:
  - name: "Mohammed Mamdouh"
  - name: "Hamzah Alanazi"
    
# Auther and collaborators 


# Other configurations
markdown: kramdown


# Optional: Set up navigation
header_pages:
  - README.md
