# Site setting 
title: "Comprehensive Workstation Configuration Guide"
subtitle: "Step-by-Step Instructions for Pre-Domain Setup, Domain Joining, and Post-Configuration"
description: "This document is a detailed guide for IT professionals tasked with setting up and configuring workstations in a domain environment, meticulously taught by [Raed Ammorah]. It covers essential steps from pre-domain setup, such as network configuration and joining a domain, to post-domain tasks like enabling Windows features, copying necessary files, and configuring security certificates. Following these instructions ensures that workstations are fully operational, secure, and aligned with organizational standards. The guide also includes important warnings and notes to prevent common errors, ensuring a smooth and efficient setup process.."

remote_theme: cotes2020/jekyll-theme-chirpy

authors:
  khalid-alkhaldi:
    name: "Khalid Alkhaldi"
    avatar: "/assets/img/khalid.png"
  mohammed-mamdouh:
    name: "Mohammed Mamdouh"
  hamzah-alanazi:
    name: "Hamzah Alanazi"
# Auther and collaborators 
copyright: "© 2024 AJF FEs"


# Other configurations
markdown: kramdown


# Optional: Set up navigation
header_pages:
  - README.md
